apiVersion: v1
kind: Pod
metadata:
  name: green-bad
  namespace: app
spec:
  containers:
  - name: green
    image: alexfeig/bluegreen
    ports:
      - containerPort: 5000
    readinessProbe:
      tcpSocket:
        port: 5000
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 5000
      initialDelaySeconds: 15
      periodSeconds: 20
    env:
      - name: app_color
        value: "green"