apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: accurics-validatingwebhookconfiguration
webhooks:
  - name: "ac.accurics.svc"
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: accurics
        name: ac
        path: /v1/k8s/webhooks/1234/scan/validate
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURUVENDQWpXZ0F3SUJBZ0lVRFNlVHdYSjYzNXo4YW53VXZOa09hZU9LU1lrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tERW1NQ1FHQTFVRUF3d2RZV011WVdOamRYSnBZM011YzNaakxtTnNkWE4wWlhJdWJHOWpZV3d3SGhjTgpNakV3TmpBeU1UZ3pOelUyV2hjTk16RXdOVE14TVRnek56VTJXakFvTVNZd0pBWURWUVFEREIxaFl5NWhZMk4xCmNtbGpjeTV6ZG1NdVkyeDFjM1JsY2k1c2IyTmhiRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTk9pWXF2SnYvN0NKRUk5TVNsZU96ck5lNVF6c3YxMmJSS1F3TFVvdmZ4TFg3K1QxMXVMY3ErTgpxUlJ3Zm9malpUcDhvQml4eldSS3B4WnBMYUlFZFNMcWYrSEhQVHc0cFFXcGs5dVQ2MXN5ODFoQ2Npdms1SWhECmM4UGtISHptQUlRZmVDcVNzWXM0T3R2aTROdXhRR3dlWDVLMk8yYzg4Wjg3TE5LUEJsN0dLQnRvaXRDWnREVXgKOHVBZHRHMksxRmxWRGR1QU96N3BqZjNNMlRRZ1B1eWw3d2svYnZvM3VZWDVVRjh1SUorVGV1MGt6cjZLK09YKwo0cGx4WjZuSFJIb3ZoVEwydE5JWFc5WURKQWtSc3RHd1lGT2hxaUl6eG5adUNYWk1YMHFKNCsxamVkOUNkaTBKClJEN01xOGV0L3FMbTBZNHBKRHdNMjMyQUZYUGRYQWNDQXdFQUFhTnZNRzB3SFFZRFZSME9CQllFRksveEZ0OUUKOGF3aTliVUpNV0JicVhPeWdsenRNQjhHQTFVZEl3UVlNQmFBRksveEZ0OUU4YXdpOWJVSk1XQmJxWE95Z2x6dApNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdHZ1lEVlIwUkJCTXdFWUlQWVdNdVlXTmpkWEpwWTNNdWMzWmpNQTBHCkNTcUdTSWIzRFFFQkN3VUFBNElCQVFBNUkrUnNOaUJnRUxRbDBXNlhYR1Zjd0NhSDFtdFQzWmdFcHNCOHlrdjMKT3BsTVJWU2J4VThQUlozTnIvVmJIazJ4cWkyKzVvTE1HRmxBcE1lWW1ibWRCSmhnTXJlY0Y2dzNEL2JDNmJkMApMTm5vMFVYTWtDNi9GM0xGbTFzai9wWEMvTHd1NW1DanRGcmhOeVk2L1YrRDIyM2lvQW81RlUvWW1CTnZaSitxClFBN2dFdmNXUUd3b1Y5UUpRbWk0cDZnaTIzbzFZZ1BhSUQrdW13NXFGVVZ3VklhOXFqQlYrR1BsdXpjNXYwdXEKQUxvcEdTU2drK0RSbU54SHViRzRpWDZCeEQ3bWNzME4wV3VJb0h2NDZkWVpPVjIyelpmSnJlVWkxSEpZNktEaQpudUxnWnBoY0NxbzVaL29Seno1SE43TUdzN005UDVIMlYxNjVHWmVTTUlmegotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
    namespaceSelector:
      matchExpressions:
      - key: environment
        operator: In
        values: ["prod"]
    rules:
    - apiGroups:
      - apps
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - deployments
      - pods